version: 2

project_name: ignorewhy

builds:
  - id: ignorewhy
    main: .
    binary: ignorewhy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/3nrikas/ignorewhy/cmd.Version={{ .Tag }}

archives:
  - ids:
      - ignorewhy
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  use: github-native
